import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layout/Navbar";
import { Suspense } from "react";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const inter = Inter({
    subsets: ["latin"],
    display: "swap",
    variable: "--font-inter",
});

import * as React from "react";

import { NextUIProvider } from "@nextui-org/react";
// app/layout.tsx
import { Providers } from "./providers";

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en" className="">
            <body>
                <Providers>
                    <Navbar />
                    <Suspense>
                        <main>{children}</main>
                    </Suspense>
                </Providers>
            </body>
        </html>
    );
}
